//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Servicio BibliotecaSoap", Namespace="http://LocalHost/WebServiceBiblioteca", ConfigurationName="ServiceReference1.ServicioBibliotecaSoap")]
    public interface ServicioBibliotecaSoap {
        
        // CODEGEN: Generating message contract since element name carnet from namespace http://LocalHost/WebServiceBiblioteca is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://LocalHost/WebServiceBiblioteca/InsertarCliente", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.InsertarClienteResponse InsertarCliente(WindowsFormsApplication1.ServiceReference1.InsertarClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCliente", Namespace="http://LocalHost/WebServiceBiblioteca", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.InsertarClienteRequestBody Body;
        
        public InsertarClienteRequest() {
        }
        
        public InsertarClienteRequest(WindowsFormsApplication1.ServiceReference1.InsertarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://LocalHost/WebServiceBiblioteca")]
    public partial class InsertarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string carnet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dpi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string direc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tel;
        
        public InsertarClienteRequestBody() {
        }
        
        public InsertarClienteRequestBody(string carnet, string nombre, string dpi, string direc, string tel) {
            this.carnet = carnet;
            this.nombre = nombre;
            this.dpi = dpi;
            this.direc = direc;
            this.tel = tel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarClienteResponse", Namespace="http://LocalHost/WebServiceBiblioteca", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.InsertarClienteResponseBody Body;
        
        public InsertarClienteResponse() {
        }
        
        public InsertarClienteResponse(WindowsFormsApplication1.ServiceReference1.InsertarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://LocalHost/WebServiceBiblioteca")]
    public partial class InsertarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarClienteResult;
        
        public InsertarClienteResponseBody() {
        }
        
        public InsertarClienteResponseBody(string InsertarClienteResult) {
            this.InsertarClienteResult = InsertarClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioBibliotecaSoapChannel : WindowsFormsApplication1.ServiceReference1.ServicioBibliotecaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioBibliotecaSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.ServicioBibliotecaSoap>, WindowsFormsApplication1.ServiceReference1.ServicioBibliotecaSoap {
        
        public ServicioBibliotecaSoapClient() {
        }
        
        public ServicioBibliotecaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioBibliotecaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBibliotecaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioBibliotecaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.InsertarClienteResponse WindowsFormsApplication1.ServiceReference1.ServicioBibliotecaSoap.InsertarCliente(WindowsFormsApplication1.ServiceReference1.InsertarClienteRequest request) {
            return base.Channel.InsertarCliente(request);
        }
        
        public string InsertarCliente(string carnet, string nombre, string dpi, string direc, string tel) {
            WindowsFormsApplication1.ServiceReference1.InsertarClienteRequest inValue = new WindowsFormsApplication1.ServiceReference1.InsertarClienteRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.InsertarClienteRequestBody();
            inValue.Body.carnet = carnet;
            inValue.Body.nombre = nombre;
            inValue.Body.dpi = dpi;
            inValue.Body.direc = direc;
            inValue.Body.tel = tel;
            WindowsFormsApplication1.ServiceReference1.InsertarClienteResponse retVal = ((WindowsFormsApplication1.ServiceReference1.ServicioBibliotecaSoap)(this)).InsertarCliente(inValue);
            return retVal.Body.InsertarClienteResult;
        }
    }
}
