USE [master]
GO

/****** Object:  Database [QuetzalExpress]    Script Date: 12/06/2015 18:24:22 ******/
CREATE DATABASE [QuetzalExpress]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuetzalExpress', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\QuetzalExpress.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'QuetzalExpress_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\QuetzalExpress_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [QuetzalExpress] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuetzalExpress].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuetzalExpress] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuetzalExpress] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuetzalExpress] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuetzalExpress] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuetzalExpress] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuetzalExpress] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [QuetzalExpress] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuetzalExpress] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuetzalExpress] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuetzalExpress] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuetzalExpress] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuetzalExpress] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuetzalExpress] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuetzalExpress] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuetzalExpress] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QuetzalExpress] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuetzalExpress] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuetzalExpress] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuetzalExpress] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuetzalExpress] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuetzalExpress] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuetzalExpress] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuetzalExpress] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QuetzalExpress] SET  MULTI_USER 
GO

ALTER DATABASE [QuetzalExpress] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuetzalExpress] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuetzalExpress] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuetzalExpress] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [QuetzalExpress] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuetzalExpress] SET  READ_WRITE 
GO

